language: ruby

sudo: false
addons:
  apt:
    packages:
    - bc
script:
# Build documentation web site
- echo 'Clone Buildroot repository'
- git clone git://git.busybox.net/buildroot
- cd buildroot
- make list-defconfigs
- echo 'raspberrypi defconfig'
- make raspberrypi_defconfig
- make 2>&1 | tee build.log | grep ">>>"

