language: ruby

sudo: false
addons:
  apt:
    packages:
    - bc
env:
  matrix:
  - DEFCONFIG_NAME=arm_foundationv8
script:
- echo 'Clone Buildroot repository'
- git clone git://git.busybox.net/buildroot
- cd buildroot
- make ${DEFCONFIG_NAME}_defconfig
- while true ; do echo "Still building" ; sleep 60 ; done &
- stupidpid=$!
- make 2>&1 | tee build.log | grep ">>>"
- kill ${stupidpid}
- scp -i ${HOME}/.ssh/buildroot-kim build.log buildroot@autobuild.buildroot.org:~/defconfigs-build/${TRAVIS_BUILD_NUMBER}-${DEFCONFIG_NAME}-${TRAVIS_JOB_ID}.log
before_install:
- mkdir -p ${HOME}/.ssh/
- openssl aes-256-cbc -K $encrypted_ff43b1ef5e6e_key -iv $encrypted_ff43b1ef5e6e_iv
  -in buildroot-kim-ssh-key -out ${HOME}/.ssh/buildroot-kim -d
