language: ruby

sudo: false
addons:
  apt:
    packages:
    - bc
env:
  matrix:
  - DEFCONFIG_NAME=acmesystems_aria_g25_128mb
  - DEFCONFIG_NAME=acmesystems_aria_g25_256mb
  - DEFCONFIG_NAME=altera_socdk
  - DEFCONFIG_NAME=altera_sockit
  - DEFCONFIG_NAME=armadeus_apf27
  - DEFCONFIG_NAME=armadeus_apf28
  - DEFCONFIG_NAME=armadeus_apf51
  - DEFCONFIG_NAME=armadeus_apf9328
  - DEFCONFIG_NAME=arm_foundationv8
  - DEFCONFIG_NAME=at91sam9260eknf
  - DEFCONFIG_NAME=at91sam9g20dfc
  - DEFCONFIG_NAME=at91sam9g45m10ek
  - DEFCONFIG_NAME=at91sam9rlek
  - DEFCONFIG_NAME=at91sam9x5ek
  - DEFCONFIG_NAME=atmel_sama5d3xek
  - DEFCONFIG_NAME=atmel_sama5d3_xplained
  - DEFCONFIG_NAME=atmel_sama5d3_xplained_mmc
  - DEFCONFIG_NAME=atmel_sama5d4ek
  - DEFCONFIG_NAME=atmel_sama5d4_xplained
  - DEFCONFIG_NAME=beaglebone
  - DEFCONFIG_NAME=calao_qil_a9260
  - DEFCONFIG_NAME=calao_tny_a9g20_lpw
  - DEFCONFIG_NAME=calao_usb_a9260
  - DEFCONFIG_NAME=calao_usb_a9263
  - DEFCONFIG_NAME=calao_usb_a9g20_lpw
  - DEFCONFIG_NAME=ci20
  - DEFCONFIG_NAME=cubieboard2
  - DEFCONFIG_NAME=cubieboard
  - DEFCONFIG_NAME=freescale_imx28evk
  - DEFCONFIG_NAME=freescale_imx31_3stack
  - DEFCONFIG_NAME=freescale_imx6dlsabreauto
  - DEFCONFIG_NAME=freescale_imx6dlsabresd
  - DEFCONFIG_NAME=freescale_imx6qsabreauto
  - DEFCONFIG_NAME=freescale_imx6qsabresd
  - DEFCONFIG_NAME=freescale_imx6sololiteevk
  - DEFCONFIG_NAME=freescale_imx6sxsabresd
  - DEFCONFIG_NAME=freescale_mpc8315erdb
  - DEFCONFIG_NAME=freescale_p1010rdb_pa
  - DEFCONFIG_NAME=freescale_p2020ds
  - DEFCONFIG_NAME=kb9202
  - DEFCONFIG_NAME=lego_ev3
  - DEFCONFIG_NAME=microzed
  - DEFCONFIG_NAME=mini2440
  - DEFCONFIG_NAME=minnowboard
  - DEFCONFIG_NAME=minnowboard_max
  - DEFCONFIG_NAME=mx53loco
  - DEFCONFIG_NAME=nitrogen6sx
  - DEFCONFIG_NAME=nitrogen6x
  - DEFCONFIG_NAME=olimex_a20_olinuxino_lime2
  - DEFCONFIG_NAME=olimex_a20_olinuxino_lime
  - DEFCONFIG_NAME=olimex_a20_olinuxino_lime_mali
  - DEFCONFIG_NAME=olimex_a20_olinuxino_micro
  - DEFCONFIG_NAME=olimex_imx233_olinuxino
  - DEFCONFIG_NAME=openblocks_a6
  - DEFCONFIG_NAME=pandaboard
  - DEFCONFIG_NAME=qemu_aarch64_virt
  - DEFCONFIG_NAME=qemu_arm_nuri
  - DEFCONFIG_NAME=qemu_arm_versatile
  - DEFCONFIG_NAME=qemu_arm_vexpress
  - DEFCONFIG_NAME=qemu_microblazebe_mmu
  - DEFCONFIG_NAME=qemu_microblazeel_mmu
  - DEFCONFIG_NAME=qemu_mips64el_malta
  - DEFCONFIG_NAME=qemu_mips64_malta
  - DEFCONFIG_NAME=qemu_mipsel_malta
  - DEFCONFIG_NAME=qemu_mips_malta
  - DEFCONFIG_NAME=qemu_ppc64_pseries
  - DEFCONFIG_NAME=qemu_ppc_g3beige
  - DEFCONFIG_NAME=qemu_ppc_mpc8544ds
  - DEFCONFIG_NAME=qemu_ppc_virtex_ml507
  - DEFCONFIG_NAME=qemu_sh4eb_r2d
  - DEFCONFIG_NAME=qemu_sh4_r2d
  - DEFCONFIG_NAME=qemu_sparc64_sun4u
  - DEFCONFIG_NAME=qemu_sparc_ss10
  - DEFCONFIG_NAME=qemu_x86_64
  - DEFCONFIG_NAME=qemu_x86
  - DEFCONFIG_NAME=qemu_xtensa_lx60
  - DEFCONFIG_NAME=qmx6
  - DEFCONFIG_NAME=raspberrypi2
  - DEFCONFIG_NAME=raspberrypi
  - DEFCONFIG_NAME=riotboard
  - DEFCONFIG_NAME=s6lx9_microboard
  - DEFCONFIG_NAME=sheevaplug
  - DEFCONFIG_NAME=snps_aarch64_vdk
  - DEFCONFIG_NAME=snps_axs101
  - DEFCONFIG_NAME=snps_axs103
  - DEFCONFIG_NAME=snps_hs38_smp_vdk
  - DEFCONFIG_NAME=snps_hs38_vdk
  - DEFCONFIG_NAME=telit_evk_pro3
  - DEFCONFIG_NAME=ts5x00
  - DEFCONFIG_NAME=udoo_quad
  - DEFCONFIG_NAME=via_imx6_vab820
  - DEFCONFIG_NAME=wandboard
  - DEFCONFIG_NAME=warpboard
  - DEFCONFIG_NAME=xilinx_zc706
  - DEFCONFIG_NAME=zedboard
script:
- echo 'Clone Buildroot repository'
- git clone git://git.busybox.net/buildroot
- cd buildroot
- make ${DEFCONFIG_NAME}_defconfig
- while true ; do echo "Still building" ; sleep 60 ; done &
- stupidpid=$!
- make 2>&1 | tee build.log | grep ">>>"
- kill ${stupidpid}
